name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
  
    - name: Install poetry
      run: |
        python -m pip install poetry==1.1.11
  
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true
    
    - name: Install dependencies
      run: |
        python -m poetry install
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
