name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Poetry
      uses: pronovic/setup-poetry@v1
      with:
        version: "1.2.0"
        plugins: "poetry-plugin-export@==1.1.2"
        cache-venv: "true"
        cache-poetry: "true"
        
    - name: Install dependencies
      run: |
        python -m poetry install
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
