name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version
        
    - name: Install dependencies
      run: |
        poetry install ../pyproject.toml
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
